baseURL = "https://pub.oribos.cn"
languageCode = "zh-cn"
title = "记事本"
copyright = "©nierheim"
googleAnalytics = ""



# paginate decides the number of the newest posts
# that'll be shown on the home page.
paginate = 18

# theme is the name of the hugo theme you're gonna use,
# `hugo-theme-minima` is put here only for debuging,
# just name it what's under your theme directory.
theme = "hugo-theme-minima"

# Author has some of your information to be shown on the home page.
[author]
name = ""
slogon = ""
description = ""


[params]

ICP = "豫ICP备2020027870号-2"
# iam is the beginning words of your self-introduction.
iam = ""
# The subtitle will be shown after the title of your blog site.
# e.g. "title - subtitle".
subtitle = ""
# Comment decides the comment plugin to be used on your blog site, 
# e.g. disqus, utterances, ovo.
comment = "false"
# Timeformat, no matter what format to use, make it the second day of Jan. 2006
timeformat = "Jan 02, 2006"
# switch for turning on/off lights.
switch = ["🌙", "🌻"]
# default theme. e.g. light, dark, system
defaultTheme = "system"
# If set true, date of posts will be shown in the homepage.
displayDate = true
# If set true, users can select text from your post.
selectable = true
# Custom global font. notice: `globalFontFamily` won't be working
# on texts in some special positions like on titles
globalFontFamily = ""
# If set true, all your posts will use the chosen comment plugin
# except those with a `comment: false` in their front-matter
commentOnAllPosts = true
# toc decides the shape of the toc button. e.g. default, lines, bar
toc = "lines"

recent = "最近更新"
older = "更早之前"

brand = "nierheim`Blog"


# Disqus configuration
[params.disqus]
shortname = ""

# Utterances configuration
# Full doc's at https://utteranc.es
# **notice**: if you're going to use utterances, you must change the 
# `repo` to your own repo address that stores comments on your site
[params.utterances]
repo = ""
issueTerm = ""

# **deprecated**
# OvO is a comment plugin written by the author of Minima.
# It is enabled when params.comment is set "ovo". You can
# have a live view on https://ovo.js.org. If you are using 
# disqus or utterance, just ignore this.
[params.ovo]
server = ""
placeholder = ""


# Params.social is an array containing your social network accounts,
# Each has a lowercase name, a svg formatted icon and a url to the 
# webpage of your account. They will be shown at the bottom of every
# page of your blog. 
# Be sure the svgs you use must have both its width and its height
# set 18. If you don't wanna put the svg code in this config file, 
# since they are too long, you can instead save them to the 
# `data/svg.toml` file under the root directory of your blog. 
# in that file, each line must be formatted as `name = '<svg>'`
# where `<svg>` is the svg code.
[[params.social]]
name = "github"  
url = "https://github.com/oribos/pub"
svg = ""
# [[params.social]]
# name = "linkedin"
# url = "https://linkedin/in/leonard-mivinci-63895317a"
# svg = ""
# [[params.social]]
# name = "twitter"
# url = "https://twitter.com/Leonard14733745"
# svg = ""
[[params.social]]
name = "rss"
url = "/index.xml"
svg = ""

# If set, titles and links of the topk newest posts extracted from 
# the feeds will be displayed in the home page. Note that the feeds
# providers have to make their 'Access-Control-Allow-Origin' contain
# your domain, otherwise the feeds cannot be fetched.
[params.friends]
feeds = [""]
topk = 3
title = ""
proxy = "" # reserved


# Menu.main is an array that's used to decide what entries can be shown
# on the navigator of yur blog. You can use a weight to make them ordered.
[[menu.main]]
name = "首页"
url = "/"
weight = 1
# [[menu.main]]
# name = "Categories"
# url = "/categories"
# weight = 2
# [[menu.main]]
# name = "Series"
# url = "/series"
# weight = 3

[[menu.main]]
name = "技术"
url = "/tech"
weight = 2
[[menu.main]]
name = "随笔"
url = "/essay"
weight = 3
# [[menu.main]]
# name = "存档"
# url = "/archives"
# weight = 98
[[menu.main]]
name = "关于"
url = "/about"
weight = 99


# You can classify your posts by setting taxanomies in the front matter
# e.g.
#     categories = ["dev"]
#     series = ["Building an RPC server"]
#     tags = ["hugo", "golang"]
# A little suggestion: one post belongs to one series or one category or multiple tags.
[taxonomies]
category = "categories"
tag = "tags"
series = "series"


# Fields below make sure all the codes in a post are
# highlighted correctly, so better not edit them.
[markup.highlight]
lineNos = true
noClasses = false
